rm(list = ls())
source("0.process_DAP_datafiles.R")
rm(list = ls())
source("1.Cohort_Descriptive_Stats.R")
rm(list = ls())
source("2.1.Survival_DAP_demographics.R")
rm(list = ls())
source("2.2.Survival_DAP_demographics.Alt.R")
rm(list = ls())
source("2.3.Survival_DAP_demographics.Alt2.R")
rm(list = ls())
source("3.Survival_CommonBreeds.R")
rm(list = ls())
source("4.1.Geography_DAP.R")
rm(list = ls())
source("4.2.Geography_DAP_vs_Human.R")
rm(list = ls())
source("5.1.HLES_SWAS_analysis.R")
rm(list = ls())
source("5.2.0.HLES_SWAS_figures.R")
rm(list = ls())
source("5.2.1.HLES_SWAS_figures_SensAn_MatureAdult.R")
rm(list = ls())
source("5.2.2.HLES_SWAS_figures_SensAn_CommonBreeds.R")
